"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PacketType = void 0;
/**
 * The different types of packets that can be sent/recieved
 */
var PacketType;
(function (PacketType) {
    PacketType[PacketType["PING"] = 0] = "PING";
    PacketType[PacketType["PLAYER_UPDATE"] = 1] = "PLAYER_UPDATE";
    PacketType[PacketType["PLAYER_MOVE"] = 2] = "PLAYER_MOVE";
    PacketType[PacketType["HEALTH_UPDATE"] = 3] = "HEALTH_UPDATE";
    PacketType[PacketType["UPGRADES"] = 4] = "UPGRADES";
    PacketType[PacketType["SELECT_ITEM"] = 5] = "SELECT_ITEM";
    PacketType[PacketType["LEADERBOARD_UPDATE"] = 6] = "LEADERBOARD_UPDATE";
    PacketType[PacketType["ATTACK"] = 7] = "ATTACK";
    PacketType[PacketType["UPDATE_STATS"] = 8] = "UPDATE_STATS";
    PacketType[PacketType["LOAD_GAME_OBJ"] = 9] = "LOAD_GAME_OBJ";
    PacketType[PacketType["PLAYER_START"] = 10] = "PLAYER_START";
    PacketType[PacketType["SET_ANGLE"] = 11] = "SET_ANGLE";
    PacketType[PacketType["PLAYER_REMOVE"] = 12] = "PLAYER_REMOVE";
    PacketType[PacketType["SELECT_UPGRADE"] = 13] = "SELECT_UPGRADE";
    PacketType[PacketType["GATHER_ANIM"] = 14] = "GATHER_ANIM";
    PacketType[PacketType["AUTO_ATK"] = 15] = "AUTO_ATK";
    PacketType[PacketType["WIGGLE"] = 16] = "WIGGLE";
    PacketType[PacketType["CLAN_CREATE"] = 17] = "CLAN_CREATE";
    PacketType[PacketType["LEAVE_CLAN"] = 18] = "LEAVE_CLAN";
    PacketType[PacketType["CLAN_REQ_JOIN"] = 19] = "CLAN_REQ_JOIN";
    PacketType[PacketType["UPDATE_HEALTH"] = 20] = "UPDATE_HEALTH";
    PacketType[PacketType["CLAN_ACC_JOIN"] = 21] = "CLAN_ACC_JOIN";
    PacketType[PacketType["CLAN_KICK"] = 22] = "CLAN_KICK";
    PacketType[PacketType["ITEM_BUY"] = 23] = "ITEM_BUY";
    PacketType[PacketType["UPDATE_AGE"] = 24] = "UPDATE_AGE";
    PacketType[PacketType["UPDATE_ITEMS"] = 25] = "UPDATE_ITEMS";
    PacketType[PacketType["CHAT"] = 26] = "CHAT";
    PacketType[PacketType["CLAN_DEL"] = 27] = "CLAN_DEL";
    PacketType[PacketType["PLAYER_SET_CLAN"] = 28] = "PLAYER_SET_CLAN";
    PacketType[PacketType["SET_CLAN_PLAYERS"] = 29] = "SET_CLAN_PLAYERS";
    PacketType[PacketType["CLAN_ADD"] = 30] = "CLAN_ADD";
    PacketType[PacketType["MINIMAP"] = 31] = "MINIMAP";
    PacketType[PacketType["UPDATE_STORE"] = 32] = "UPDATE_STORE";
    PacketType[PacketType["DISCONN"] = 33] = "DISCONN";
    PacketType[PacketType["WINDOW_FOCUS"] = 34] = "WINDOW_FOCUS";
    PacketType[PacketType["PLAYER_ADD"] = 35] = "PLAYER_ADD";
    PacketType[PacketType["SPAWN"] = 36] = "SPAWN";
    PacketType[PacketType["IO_INIT"] = 37] = "IO_INIT";
    PacketType[PacketType["UPDATE_ANIMALS"] = 38] = "UPDATE_ANIMALS";
    PacketType[PacketType["CLAN_LIST"] = 39] = "CLAN_LIST";
    PacketType[PacketType["BUY_AND_EQUIP"] = 40] = "BUY_AND_EQUIP";
    PacketType[PacketType["DEATH"] = 41] = "DEATH";
    PacketType[PacketType["CLAN_NOTIFY_SERVER"] = 42] = "CLAN_NOTIFY_SERVER";
    PacketType[PacketType["CLAN_NOTIFY_CLIENT"] = 43] = "CLAN_NOTIFY_CLIENT";
    PacketType[PacketType["HEALTH_CHANGE"] = 44] = "HEALTH_CHANGE";
    PacketType[PacketType["JOIN_REQUEST"] = 45] = "JOIN_REQUEST";
    PacketType[PacketType["REMOVE_GAME_OBJ"] = 46] = "REMOVE_GAME_OBJ";
    PacketType[PacketType["UPDATE_PLACE_LIMIT"] = 47] = "UPDATE_PLACE_LIMIT";
    PacketType[PacketType["ADD_PROJECTILE"] = 48] = "ADD_PROJECTILE";
    PacketType[PacketType["UPDATE_PROJECTILES"] = 49] = "UPDATE_PROJECTILES";
})(PacketType || (PacketType = {}));
exports.PacketType = PacketType;
